#!/bin/bash

for diff_file in ~/.doom.d/diffs/*; do
    if [[ $diff_file == *'.bk' ]]; then
        continue
    fi

    echo $diff_file
    package=$((basename $diff_file) | sed 's/.diff//')
    echo $package

    if [ -d ~/.emacs.d/.local/straight/repos/${package} ]; then
        cd ~/.emacs.d/.local/straight/repos/${package}
        echo ~/.emacs.d/.local/straight/repos/${package}

        git diff > ${diff_file}.bk
        if [ -s ${diff_file}.bk ]; then

            if cmp -s ${diff_file}.bk ${diff_file}; then
                echo "No changes"
                rm ${diff_file}.bk
            else
                diff ${diff_file}.bk ${diff_file}
                read -r -p "Apply changes? [y/N] " response
                if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]];then
                    echo "Applying changes"
                    mv ${diff_file}.bk ${diff_file}
                else
                    echo "No changes"
                    rm ${diff_file}.bk
                fi
            fi
        else
            rm ${diff_file}.bk
        fi
        git stash save --keep-index --include-untracked

        cd -
    fi


done


VER=`emacs --version | head -n 1 | awk '{print $3}'`

if [[ $1 == 'not_upgrade' ]]; then
    echo "Not upgrading packages"
else
    echo "Upgrading packages"
    export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;export ALL_PROXY=socks5://127.0.0.1:1080
    STASH_NAME=$(date '+%Y-%m-%d-%H:%M:%S')

    cd ~/.emacs.d
    #git stash push -m $STASH_NAME
    ~/.emacs.d/bin/doom upgrade --force
    #git stash apply stash@{0}

    # delete package
    for package in $(git diff | grep "package\!" | grep "^+" | sed "s/^.*e! \(.*\) :pin.*/\1/")
    do
        echo $package
        rm -rf ~/.emacs.d/.local/straight/repos/${package}
        rm -rf ~/.emacs.d/.local/straight/build-${VER}/${package}
    done
    ~/.emacs.d/bin/doom sync
    cd -
fi

rm -rf ~/.emacs.d/.local/straight/build-${VER}/eaf ~/.emacs.d/.local/straight/build-${VER}/jupyter


for diff_file in ~/.doom.d/diffs/*; do
    echo $diff_file
    cd ~/.emacs.d/.local/straight/repos/$((basename $diff_file) | sed 's/.diff//')
    rm -rf ~/.emacs.d/.local/straight/build-${VER}/$((basename $diff_file) | sed 's/.diff//')
    git apply ${diff_file}
    cd -
done


~/.emacs.d/bin/doom sync
